[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[variables]
NEXT_TELEMETRY_DISABLED = "1"
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
CI = "true"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["NODE_ENV=production npm run build"]

[start]
cmd = "NODE_ENV=production npm run start"
