export const ROUTES = {
  home: "/",
  about: "/about",
  shop: "/products",
  services: "/services",
  contact: "/contact",
  order: "/checkout",
  account: "/account",
  login: "/login",
  register: "/register",
  cart: "/cart",
  checkout: "/checkout",
  discover: "/about",
  dashboard: "/dashboard",
  dashboardLogin: "/dashboard/login",
  dashboardOrders: "/dashboard/orders",
  dashboardProducts: "/dashboard/products",
  dashboardProductNew: "/dashboard/products/new",
  dashboardProductEdit: (id: string) => `/dashboard/products/${id}/edit` as const,
  dashboardCategories: "/dashboard/categories",
  dashboardCategoryNew: "/dashboard/categories/new",
  dashboardCategoryEdit: (id: string) =>
    `/dashboard/categories/${id}/edit` as const,
  dashboardSubscribers: "/dashboard/subscribers",
  dashboardSettings: "/dashboard/settings",
} as const;
